export = {
    VK_GROUP_ID: 0,
    VK_API_KEY: '',

    TELEGRAM_API_KEY: '',
    TELEGRAM_CHANNEL_ID: '',

    DISCORD_API_KEY: '',
    DISCORD_CHANNEL_NAME: '',

    GITHUB_API_KEY: '',
    GITHUB_USERNAME: '',
    GITHUB_REPO_NAME: ''
}